### ISSUE TITLE
AttributeError: 'int' object has no attribute '_root'

### ISSUE THREAD

**Issue by Over2You** [fishyboteso/fishyboteso#142]
> C:\Program Files\Python310\lib\runpy.py:126: RuntimeWarning: 'fishy.__main__' found in sys.modules after import of package 'fishy', but prior to execution of 'fishy.__main__'; this may result in unpredictable behaviour
warn(RuntimeWarning(msg))
created backup
launching please wait...
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\acnig\AppData\Roaming\Python\Python310\site-packages\fishy\__main__.py", line 105, in <module>
    main()
  File "C:\Users\acnig\AppData\Roaming\Python\Python310\site-packages\fishy\__main__.py", line 84, in main
    if not gui.check_eula():
  File "C:\Users\acnig\AppData\Roaming\Python\Python310\site-packages\fishy\gui\terms_gui.py", line 16, in check_eula
    _run_terms_window()
  File "C:\Users\acnig\AppData\Roaming\Python\Python310\site-packages\fishy\gui\terms_gui.py", line 43, in _run_terms_window
    check_value = tk.IntVar(0)
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 564, in __init__
    Variable.__init__(self, master, value, name)
  File "C:\Program Files\Python310\lib\tkinter\__init__.py", line 372, in __init__
    self._root = master._root()
AttributeError: 'int' object has no attribute '_root'

All I do with YT tutorial powershell runing as admin and all install and upgrade done without problems just last line with runing bring back this error.

How to solve it ?

**Comment by SemjonWilke** [comment]
You are using Python 3.10. Fishy only works on 3.7.
See https://github.com/fishyboteso/fishyboteso/wiki/Installation
